### PR TITLE
Use Redux in React components

### PR DESCRIPTION
**Pull request by fickryiman**
- Create an initialState variable
- Display books, received from the slice, in a reusable component
- Dispatch actions using useDispatch
- Add a <Button> component, which includes: An event handler that adds a book to the books array (with attributes id, title and author)
- Add a <Button> component, which includes: An event handler that removes a book from the books array (by id)

### CODE REVIEW

**Review by DammyShittu — COMMENTED** [review]
Hi @fickryiman,

While you made a great effort in this project, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a project that has no linter checks. Kindly ensure your linter checks for this PR are running.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by shella12 — COMMENTED** [review]
Hi @fickryiman, 

#  Status: Invalidated :red_circle: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that 

- [x] has linter errors. Please include node_modules to `.gitignore` file so it doesn't get pushed to the github. Also please delete the node_module from your repository to fix linter errors

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by fickryiman** [comment]
I have included node_modules on my .gitignore file, and I don't have node_modules on my repository

**Review by thecodechaser — APPROVED** [review]
## STATUS: APPROVED 🟢

## Hi @fickryiman👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉
- Nice UI design. ✔️
- No linter errors. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- PR has a good title and summary. ✔️



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
